### ISSUE TITLE
HA Core 2023.5 - Connection failure after upgrade

### ISSUE THREAD

**Issue by ryandkg** [IngoS11/ha-schluter#11]
After installing the latest Core upgrade, the integration no longer connects.

I have tried uninstalling the integration, reinstalling and providing the correct Schluter login credentials.

**2023-05-04_ 13:35:04.859 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration schluter which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-05-04 13:36:56.580 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxxxx@gmail.com for schluter
File "/config/custom_components/schluter/__init__.py", line 47, in  #async_setup_entry**

Similar errors are also observed in other integrations (ONVIF and Tuya_v2) ie involving #async-setup-entry.

Connectivity is restored by reverting to version 2023.4.6

**Comment by squirtbrnr** [comment]
changing line 47 of `__init__.py` from `hass.config_entries.async_setup_platforms(entry, PLATFORMS)` to `hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)` allows the integration to load and fixes this error.  However, the entities are not available.  I'm working through this issue trying to get it working again.  Unfortunately, the code owner is not maintaining this.  You'll have to either fork the repo yourself or make the changes locally.
