### ISSUE TITLE
Will this work for users based in the UK?

### ISSUE THREAD

**Issue by rajp1503** [IngoS11/ha-schluter#13]
I have 4 UFH heating zones in my home which are controlled by the Schluter Ditra Heat E Wifi apps. I have all 4 setup using onscreen steps on the app and registered to an email address and password. When I try to provide this info into the login screen, I keep getting invalid username or password.. wonder if this works for anyone based in the UK as Schluter do not provide a portal for users to log into. If not, what could be the issue??

**Comment by IngoS11** [comment]
Hi @rajp1503. I am from the US and only have one single zone. Do you happen to know the URL that is used in the UK?

**Comment by IngoS11** [comment]
Closed in favour of #14
